### ISSUE TITLE
Iron bushing set recipe issue

### ISSUE THREAD

**Issue by WildStarorion** [GreatOrator/SpaceOdyssey#11]
When trying to make the iron bushing for research in AW, I get Iron frame form advanced generators instead,  I tried both in AW crafting table and regular vanilla crafting table.  We might need to change a recipe.

**Comment by GreatOrator** [comment]
hmmm, the advanced generators MIGHT be possible to change...but would mean another mod to add...i'll see if I can figure something out.

**Comment by GreatOrator** [comment]
Considering either crafting manager or no more recipe conflicts...probably crafting manager since I can change the vanilla recipe for advanced generators.

**Comment by InfinityRaider** [comment]
What about TConstruct casting recipes for the bushings?

**Comment by GreatOrator** [comment]
well, not without using mine and modtweaker.  Crafting manager would be the easiest to make happen actually

**Comment by WildStarorion** [comment]
i thought there was a mod that allowed for you to craft different items with the same parts but was a slider or a button to click that switched between them

**Comment by GreatOrator** [comment]
only works with vanilla crafting table recipes.  Most of AW requires its own table

**Comment by GreatOrator** [comment]
Advanced generators has been removed and will be replaced by immersive engineering, so closing issue.
