### ISSUE TITLE
agricraft crash

### ISSUE THREAD

**Issue by birdiegirl** [GreatOrator/SpaceOdyssey#12]
morvash was looking in NEI for sugarcane seed recipe and as soon as he clicked on the seeds to pull up the recipe, he crashed.   he was able to replicate the crash twice.

**Comment by GreatOrator** [comment]
I would need a link to the crash report, should post to pastebin and then put a link here.

**Comment by InfinityRaider** [comment]
Yes, post crash report please

**Comment by GreatOrator** [comment]
Still being tested, but seems to be coincidence related to memory on a laptop.

**Comment by GreatOrator** [comment]
No further reports, so will close this out.
