### ISSUE TITLE
Aridite Issue with pick axe head mold

### ISSUE THREAD

**Issue by WildStarorion** [GreatOrator/SpaceOdyssey#13]
Unable to use aridite to make a pick axe head from smeltery.  it will not pour into the mold.  Not listed as a material on mold either

**Comment by GreatOrator** [comment]
Will try to test this out tonight to see if it is just a matter of progression limited by Iguana, of a true bug.

**Comment by WildStarorion** [comment]
Go I think this was a issue with .5.3 version I was running.  This does not seem to be a issue in the .5.4 world i am in.

**Comment by GreatOrator** [comment]
Excellent, then I will close this issue :D
