### ISSUE TITLE
Catacombs causing crash

### ISSUE THREAD

**Issue by GreatOrator** [GreatOrator/SpaceOdyssey#14]
BvB has run across a possible issue with the Gravestone catacombs crashing upon generating in the world.

http://pastebin.com/D2V7v2M2

Can anyone else replicate this.  Similar issue to what happened in TC and the reason they were disabled in that pack.

**Comment by WildStarorion** [comment]
I have not seen this yet Go,  I have explored 3 different .5.4 worlds now.

**Comment by GreatOrator** [comment]
Since we have not had any more reports of this I will close this for now.  It may be a non-issue going forward depending on the changes in the pack that are planned
