### ISSUE TITLE
Config Change Suggestion - Mega Rubber tree sapling removal

### ISSUE THREAD

**Issue by WildStarorion** [GreatOrator/SpaceOdyssey#18]
Go as we talked in Skype, you might want to remove mega rubber tree sapling from chest rewards.  It make a huge rubber tree the size of a red wood  Also this might be used to grieve a base or 2 if you build it to close.

**Comment by GreatOrator** [comment]
what mod does this come from?  MFR?

**Comment by GreatOrator** [comment]
Yeah MFR, disabled it in the loot tables
