### ISSUE TITLE
[Suggestion] Mod that adds gravity

### ISSUE THREAD

**Issue by InfinityRaider** [GreatOrator/SpaceOdyssey#21]
Starminer mod: http://forum.minecraftuser.jp/viewtopic.php?f=13&t=17975
It's a japanese mod, it adds a few fun things, such as gravity controllers, like a very dense object that will allow you to walk on the sides of blocks (configurable range and intensity), velcro that lets you walk on walls and ceilings, and its own dimension.
Of course the only thing htis would be used for is the gravity controller, unless you have some other thoughts or ideas.

**Comment by GreatOrator** [comment]
Been looking at it, the license seems a bit ambiguous though and does not seem to be regularly updated (at least the english port)

**Comment by InfinityRaider** [comment]
Thats just a matter of localization, and if IIRC @BBoldt once went to him to go and ask permissions: see here http://forum.minecraftuser.jp/viewtopic.php?f=13&t=17975&start=140#p214941

**Comment by GreatOrator** [comment]
With planned changes in the direction of the pack, gravity is most likely not going to be a thing at this time...but trust me, the change will be worth it :)
