### ISSUE TITLE
Flan's Mod Crash

### ISSUE THREAD

**Issue by Atroxil** [GreatOrator/SpaceOdyssey#23]
I encountered a bug with Flan's Mod.  I was attempting to modify a NSCD sniper rifle in the tile.NSCD.box and every time i open up its GUI, the game CTD. I can open up the GUI for the other gun modifier boxes, but not that one.  It could be due to creatively creating the gun, or boxes - I'm not sure.  I tried crafting the box and got the same issue.

http://pastebin.com/UUBsfztB

**Comment by GreatOrator** [comment]
hmmm, can you tell what package for flan's that gun is from?

**Comment by Atroxil** [comment]
It looks like Flan's Future Craft, though it may be apart of others as well.
http://www.minecraft-smp.de/mediawiki/index.php/FutureCraft_Content_Pack

**Comment by GreatOrator** [comment]
Can you try some of the items from other packages?

**Comment by GreatOrator** [comment]
With the upcoming changes, I simply removed the add-ons which should remove the crash as well.  Problem is the add-ons are not well documented and most likely are not up-to-date with flans.
