### ISSUE TITLE
Hotbar issue with shift clicking

### ISSUE THREAD

**Issue by BvB1979** [GreatOrator/SpaceOdyssey#5]
Unable to shift click items from your hotbar to your main inventory. Not sure which mod is causing this though.

Edit: You can if you have another inventory up such as the crafting table.

**Comment by GreatOrator** [comment]
Issue appears to have been caused by galacticraft.  Now that it is removed everything seems to be working perfectly

**Comment by eDilettante** [comment]
Still seems to be an issue for me - looks more like it's something to do with the camping(?) mod - whatever the one that adds the swiss-army knife... Just started a new world, fresh install, the default inventory screen has four tabs, MC, backpack (with backpack icon), crafting (with knife logo) and config (with cog logo) - I've noticed before that if you go into config and tell it not to edit MC inventory you lose the backpack/crafting tabs and get the NPCQuesting tabs in their place... and they are then the default tabs for any new games you create unless you do a full fresh install...

**Comment by eDilettante** [comment]
looks like it may be 'camping.cfg', in the 'general' section - # Primary inventory option, is settable in the Camping Inventory! [range: 0 ~ 2, default: 0]
    I:"Primary Inventory Option"=0
changes to =2 when you go into the config tab and tell it not to edit MC inventory... (yes, i'll pop this in github as well ;-)

**Comment by eDilettante** [comment]
In camping.cfg:
Set "Primary Inventory Option"=1
Leave "Secondary Inventory Option"=0 (default)

This gives you the NPC/questing/armor/dual-wield tabs in inventory, but adds a backpack icon to the main inventory tab that gives access to the camping backpack/crafting inventory tabs (then reverts to the NPC/questing tabs once you exit inventory and go back into it.
