### ISSUE TITLE
Unable to download ColoradoCity-DefaultFC.zip

### ISSUE THREAD

**Issue by WhisperFire26** [GreatOrator/SpaceOdyssey#64]
I am attempting to install FallCraft 1.0.10 and got a 404 ERROR when I attempted to download the map. Please tell me that you still have the files for ColoradoCity-DefaultFC.zip. I want to record a YouTube series with my friends. Please help!

**Comment by GreatOrator** [comment]
Since you posted this request in basically every location Available I am simply closing this one because it has already been answered.
