### ISSUE TITLE
spawn point not registering after sleeping in bed from crystal ball

### ISSUE THREAD

**Issue by birdiegirl** [GreatOrator/SpaceOdyssey#7]
i used the crystal ball and chose single, slept in the bed upstairs.  died a bit later and was put back at spawn saying it did not register my bed.    will let you know if it repeats after I die again :)

**Comment by GreatOrator** [comment]
With that new feature of MCA I am actually considering dropping it from the pack.  The idea of marriage and starting out with a family does not fit well with what I envision from the pack and there is no way to disable that orb.  I mean, when you get to earth, how do you magically now have a family if there are supposedly no other humans on earth?

**Comment by GreatOrator** [comment]
Issue resolved, just going to remove MCA as discussed.
