### ISSUE TITLE
OreGen and it's duplicates

### ISSUE THREAD

**Issue by birdiegirl** [GreatOrator/SpaceOdyssey#9]
I am getting both thermal expansion and IC2 copper

**Comment by eDilettante** [comment]
Same, mainly TE, at around lvl 50-55, but just found a patch of IC2 at lv l55-60

**Comment by GreatOrator** [comment]
Ok, found out why, but will leave this open until confirmed after next update (not today though). Forgot and left IC2 to do it's own oregen, disabled that and added uranium to the cofh world gen configs

**Comment by GreatOrator** [comment]
Should be fixed in newly created maps.
